plugins {
    id 'com.android.application'
}

android {
    namespace 'com.fanmade.dg'
    compileSdk 35

    defaultConfig {
        applicationId 'com.fanmade.dg'
        minSdk 26
        targetSdk 35
        versionCode 17
        versionName '0.1.7'

        externalNativeBuild {
            cmake {
                cppFlags '-std=c++17 -O2 -ffast-math'
            }
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            debuggable false
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.31.6'
        }
    }
}
